/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccountTree"): TruffleContracts.AccountTreeContract;
      require(name: "Batch"): TruffleContracts.BatchContract;
      require(
        name: "BLSAccountRegistry"
      ): TruffleContracts.BLSAccountRegistryContract;
      require(name: "DepositManager"): TruffleContracts.DepositManagerContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "FraudProof"): TruffleContracts.FraudProofContract;
      require(
        name: "FraudProofTreeUtils"
      ): TruffleContracts.FraudProofTreeUtilsContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MockFraudProof"): TruffleContracts.MockFraudProofContract;
      require(name: "MockRollup"): TruffleContracts.MockRollupContract;
      require(name: "MockToken"): TruffleContracts.MockTokenContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Rollup"): TruffleContracts.RollupContract;
      require(name: "RollupTree"): TruffleContracts.RollupTreeContract;
      require(name: "StakeManager"): TruffleContracts.StakeManagerContract;
      require(name: "StateAccount"): TruffleContracts.StateAccountContract;
      require(
        name: "TestAccountTree"
      ): TruffleContracts.TestAccountTreeContract;
      require(name: "TestBLS"): TruffleContracts.TestBLSContract;
      require(name: "TestBytes"): TruffleContracts.TestBytesContract;
      require(
        name: "TestFraudProofTreeUtils"
      ): TruffleContracts.TestFraudProofTreeUtilsContract;
      require(
        name: "TestStateAccount"
      ): TruffleContracts.TestStateAccountContract;
      require(name: "TestTx"): TruffleContracts.TestTxContract;
      require(name: "TokenRegistry"): TruffleContracts.TokenRegistryContract;
      require(name: "Tx"): TruffleContracts.TxContract;
      require(name: "Withdraw"): TruffleContracts.WithdrawContract;
    }
  }
}
